<!------- Smart Header Include File---------->
<?php include '../../../smart/html/includes/smart-header.php'; ?>
<!------- Smart Header Include File end---------->

<!------- CMS Stylesheet------=------->
<link rel="stylesheet" href="../../css/cms.css">
<!------- CMS Stylesheet end---------->

<div class="container-fluid p15 p-md30">
	<!------- Header Start----------->
	<div class="row mb15 mb-md30">
		<div class="col-12">
		<span class="f-md-24 f-20 lato-font">XML </span> &nbsp;
		<a href="#" class="gblue-clr t-decoration-none f-17" data-toggle="modal" data-target="#helpModal"><i class="icon-text-help"></i></a>
		<a href="#" class="gblue-clr t-decoration-none f-17" data-toggle="modal" data-target="#vhelpModal"><i class="icon-video-help"></i></a>
		<p class="lightgrey mt5">Define your email message details here</p>
		</div>
	</div>
	<!------- Header End ----------->
	
	<!---------XML Section Start---------->
	<div class="row">
		<div class="col-md-4 col-lg-3 col-xl-3 mb15 mb-md0">
		<div class="nav flex-column nav-pills ui-vertical-tab f-16 w400">
            	<a class="nav-link active" href="site-map-basic-option.php"><i class="icon-xml"></i>CMS Sitemap Basic Options</a>
				<a class="nav-link" href="site-map-additional-pages.php"><i class="icon-xml"></i>Additional Pages</a>
				<a class="nav-link" href="post-priority.php"><i class="icon-xml"></i>Post Priority</a>
				<a class="nav-link" href="sitemap-content.php"><i class="icon-xml"></i>Sitemap Content</a>
				<a class="nav-link" href="exclude-items.php"><i class="icon-xml"></i>Excluded Items</a>
				<a class="nav-link" href="change-frequencies.php"><i class="icon-xml"></i>Change Frequencies</a>
				<a class="nav-link" href="priorities.php"><i class="icon-xml"></i>Priorities</a>
			</div>
		</div>
		<div class="col-md-8 col-lg-9 col-xl-9 col-12">
         
			<div class="d-flex smart-checkbox-btn checkbox-strong-blue">
			<input id="updates" name="" type="checkbox">
			<label for="updates" class="mb0">Notify Google about updates of your Blog</label>
			</div>
			<div class="f-12 mt5 ml28 d-gblue-clr">No registration required, but you can join the <a href="#" class="p-blue-clr t-decoration-none"> Google Webmaster Tools </a> to check crawling statistics.</div>
			
			<div class="mt-md30 mt15">
			<div class="d-flex smart-checkbox-btn checkbox-strong-blue">
			<input id="updates2" name="" type="checkbox">
			<label for="updates2" class="mb0">Notify Bing (formerly MSN Live Search) about updates of your Blog</label>
			</div>
			<div class="f-12 mt5 ml28 d-gblue-clr">No registration required, but you can join the <a href="#" class="p-blue-clr t-decoration-none"> Bing Webmaster Tools </a> to check crawling statistics.</div>
			</div>
			
			<div class="mt-md30 mt15">
			<div class="d-flex smart-checkbox-btn checkbox-strong-blue">
			<input id="updates3" name="" type="checkbox">
			<label for="updates3" class="mb0">Add sitemap URL to the virtual robots.txt file.</label>
			</div>
			<div class="f-12 mt5 ml28 d-gblue-clr">The virtual robots.txt generated by WordPress is used. A real robots.txt file must NOT exist in the blog directory!</div>
			</div>
			
			<div class="row smart-form mt-md50 mt15">
				<div class="col-12 f-18 w700 lato-font">Advanced options</div>
				<div class="col-md-12 col-lg-6 col-12 mt-lg30 mt15 d-gblue-clr">
					<label>Try to increase the execution time limit to</label>
					<input type="text" class="form-control" value="50">
					<div class="f-12 mt5">(in seconds, e.g. "60" or "0" for unlimited)</div>
				</div>
				<div class="col-md-12 col-lg-6 col-12 mt-lg30 mt15 d-gblue-clr">
					<label>Try to increase the memory limit to</label>
					<input type="text" class="form-control" value="4m">
					<div class="f-12 mt5">(e.g. "4M" , "16M")</div>
				</div>
				<div class="col-md-12 col-lg-6 col-12 mt-lg30 mt15 d-gblue-clr">
					<label>Override the base URL of the sitemap</label>
					<input type="text" class="form-control" value="50">
				</div>
				<div class="col-12 f-14 w400 mt-md30 mt15">Use this if your blog is in a sub-directory, but you want the sitemap be located in the root. Requires .htaccess modification</div>
				
				<div class="col-12 text-right mt-md30 mt15">
				  <input type="submit" value="Save" class="base-btn blue-btn">
				</div>
			</div>
          		  
		</div>
	</div>
	<!---------XML Section End---------->
</div>

<!------- Smart Footer Include File---------->
<?php include '../../../smart/html/includes/smart-footer.php'; ?>
<!------- Smart Footer Include File end ---------->